basePath: /
definitions:
  request.Request:
    properties:
      method:
        type: string
      path:
        type: string
      role:
        type: string
      user_id:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: manipulate data from Kafka
  title: Access Control Service
  version: "1.0"
paths:
  /access-control:
    post:
      parameters:
      - description: model_type
        in: body
        name: model_type
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/request.Request'
        "400":
          description: Bad Request
          schema:
            type: HTTPError
      summary: manipulate message from Kafka
      tags:
      - access-control
  /casbin/{role}:
    get:
      parameters:
      - description: role
        in: path
        name: role
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            type: HTTPError
      summary: return of api that role can access to
      tags:
      - casbin
  /general/{type}:
    get:
      parameters:
      - description: type
        in: path
        name: type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            type: HTTPError
      summary: Show the list of objects by limit input.
      tags:
      - general
    post:
      parameters:
      - description: type
        in: path
        name: type
        required: true
        type: string
      - description: model-value
        in: body
        name: model-value
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            type: HTTPError
      summary: Create Object with Specified Type
      tags:
      - general
  /general/{type}/{id}:
    delete:
      parameters:
      - description: type
        in: path
        name: type
        required: true
        type: string
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            type: HTTPError
      summary: Deactive object by user_id
      tags:
      - general
    get:
      parameters:
      - description: type
        in: path
        name: type
        required: true
        type: string
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            type: HTTPError
      summary: Get active object by Id
      tags:
      - general
    put:
      parameters:
      - description: type
        in: path
        name: type
        required: true
        type: string
      - description: id
        in: path
        name: id
        required: true
        type: string
      - description: model_value
        in: body
        name: model_value
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            type: HTTPError
      summary: Update specified object with id
      tags:
      - general
swagger: "2.0"
