basePath: /
definitions:
  request.Request:
    properties:
      method:
        type: string
      path:
        type: string
      role:
        type: string
      user_id:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: manipulate data from Kafka
  title: Access Control Service
  version: "1.0"
paths:
  /access-control:
    post:
      parameters:
      - description: model_type
        in: body
        name: model_type
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/request.Request'
        "400":
          description: Bad Request
          schema:
            type: HTTPError
      summary: manipulate date
      tags:
      - access-control
swagger: "2.0"
